apiVersion: v1
kind: Pod
Metadata:
  Name: multip-container
  labels:
    project: roboshop
    purpose: multi-container-demo

spec:
  containers:
  - name: nginx 
    image: nginx
  - name: almalinux
    image: almalinux:9  
    command: ["sleep", "1000"]