apiVersion: v1
kind: Pod
metadata:
  name: annotataions
  labels:
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is created to demonstrate pod annotations"
    jenskins: "https://jenkins.com/build/job/roboshop-catalogue/3"
spec:
  containers:
  - name: nginx
    image: nginx    