apiVersion: v1
kind: Pod
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    requests: # soft limit
        memory: "68Mi"
        cpu: "100m"
    limits: # hard limit
        memory: "128Mi"
        cpu: "150m"



















